### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by lucalanca** [tandibar/ng-rollbar#10]
Is it possible to publish this also on npm?

**Comment by tandibar** [comment]
Yes, it is possible but i would love to know why. You will always need angular for ng-rollbar to work and why would you develop with angular in node? I would really like to know what your usecase is.

**Comment by lucalanca** [comment]
You can also use npm packages on the browser (with webpack or browserify, for example). Actually, angular itself is also published on npm (https://www.npmjs.com/package/angular). 

I think bower will eventually be replaced by npm. Meanwhile, why not make your package available on both?

**Comment by piotrd** [comment]
I have the same use case as @lucalanca. In my (large) project I use browserify and I am forced to use both bower and npm, because some packages do not publish to npm. If they did, I would be able to use npm only and skip the hassle with "managing" two package managers.

**Comment by tandibar** [comment]
Ok, i get it. I published the package at npm: https://www.npmjs.com/package/ng-rollbar
I will integrate this in my build process to always publish to npm and bower.

**Comment by lucalanca** [comment]
@tandibar perfect. Thanks for being open about it. :dancers:
