### ISSUE TITLE
Type error when calling Rollbar.info()

### ISSUE THREAD

**Issue by douglasward** [tandibar/ng-rollbar#18]
Hi there, 

when I use any of the severity api calls to throw an error, I get the following type error in the console:
`[Rollbar]: TypeError: this._getLogArgs is not a function`

Using Rollbar.Rollbar.info() works however.

Would be great if this could be fixed! Many thanks in advance.

**Comment by tandibar** [comment]
Could you please give me some more information about your szenario? Are you calling `RollbarProvider.init` in module configuration? Am I getting you right that you cannot call `Rollbar.error` or any of the other rollbar functions?

**Comment by tandibar** [comment]
Closing due to no response.
