### ISSUE TITLE
Bump to 1.4.1+

### ISSUE THREAD

**Issue by piotrd** [tandibar/ng-rollbar#2]
Hi,

Could you please bump Rollbar lib to 1.4.1? https://github.com/rollbar/rollbar.js/blob/v1.4.1/dist/rollbar.snippet.js

**Comment by didlich** [comment]
1.4.2 was released recently

**Comment by piotrd** [comment]
There is a thread about the same (necessity of updating the Rollbar snippet with every release) in a "sibling" library for Ember. Cory mentiones a convenient way of rebuilding the lib when there's a need. Maybe the same could be implemented here.

**Comment by didlich** [comment]
@piotrd could you post the thread link?

**Comment by piotrd** [comment]
Sorry, I meant to, but eventually I forgot. Here it is: https://github.com/rollbar/rollbar.js/issues/104#issuecomment-116811986
