### ISSUE TITLE
ng-rollbar v1.9.1 seems to be pointing to rollbar v1.9.0

### ISSUE THREAD

**Issue by hneiva** [tandibar/ng-rollbar#20]
With ng-rollbar 1.9.1:

```
RollbarNotifier.NOTIFIER_VERSION
> "1.9.0"
```

Ignore this if I'm just being stupid.

**Comment by tandibar** [comment]
You are right, thanks for figuring this out. The problem is in the rollbar.js repo itself, see https://github.com/rollbar/rollbar.js/commit/76ca1a3cc442f94ac3e462cf18336c3564de3724
