### ISSUE TITLE
Update docs to include minification-safe dependency injection

### ISSUE THREAD

**Issue by jamesjryan** [tandibar/ng-rollbar#25]
Please update the docs to make the initialisation example minification-safe by naming RollbarProvider as a dependency.

`myApp.config(['RollbarProvider', function(RollbarProvider) {
  RollbarProvider.init({
    accessToken: "<YOUR-APPLICATION-TOKEN>",
    captureUncaught: true,
    payload: {
      environment: '<specify-your-env>'
    }
  });
}]);`

Had me scratching my head why my build was breaking after including the module.

Otherwise great module and a happy camper!

**Comment by tandibar** [comment]
Do not know if you already know it, but my tip is to use [ng-annotate](https://github.com/olov/ng-annotate) in your build process. Makes life easier :-)
