### ISSUE TITLE
Rollbar.error not sending through extra parameters

### ISSUE THREAD

**Issue by fiddledsticks** [tandibar/ng-rollbar#26]
When I use Rollbar.error (possibly also affecting info, warning, etc) and pass through a second parameter it doesn't send through e.g. `Rollbar.error('login_error', {user_id: 123})`. I would expect that to send through the user_id as an extra parameter. It works if I use the original Rollbar instance like ``Rollbar.Rollbar.error('login_error', {user_id: 123})`.

**Comment by nrutman** [comment]
This was fixed in #19 but has not been released as a version yet.

**Comment by nrutman** [comment]
@tandibar, is there a way to release a version of your module without the need for a new version of `rollbar.js`, or are we waiting on them to release their next version before this module can be updated?

**Comment by tandibar** [comment]
I released a new version `1.9.2` with the patch. Hope that it does not get to confusing with the version numbers as there is no corresponding release at [rollbar.js](https://github.com/rollbar/rollbar.js).
Perhaps i should not try to stick with the rollbar release numbers...

**Comment by nrutman** [comment]
@tandibar, since you don't have explicit control over when Rollbar releases a new version, I personally wouldn't try to couple `ng-rollbar` versioning with `rollbar-browser` versioning.
