### ISSUE TITLE
RoR + AngularJS injector module failed to instantiate module

### ISSUE THREAD

**Issue by develaper** [tandibar/ng-rollbar#30]
I am trying to add ng-rollbar to my RoR+AngularJS project. The stack is:ruby 2.3.1p112, Rails 4.2.6 and angularJS 1.4.12. Following the instructions I runned the command:

   ` bower install ng-rollbar --save`
Here is my bower.json after that:

```
{
 "name": "dsl-generated dependencies",
 "dependencies": {
 "foundation-sites": "~6.2.3",
 "jquery-ujs": "~1.2.1",
 "angular": "~1.4.12",
 "angular-sanitize": "~1.4.12",
 "angular-cookies": "~1.4.12",
 "angular-route": "~1.4.12",
 "angular-resource": "~1.4.12",
 "angular-local-storage": "~0.2.7",
 "angular-scroll-glue": "~2.0.7",
 "components-font-awesome": "~4.6.3",
 "pusher": "~3.1.0",
 "pusher-angular": "~0.1.9",
 "angular-payments": "git://github.com/laurihy/angular-payments#9643191f23",
 "angular-moment": "~0.10.3",
 "angular-xeditable": "~0.2.0",
 "zInfiniteScroll": "~1.1.4",
 "motion-ui": "~1.2.2",
 "angular-toastr": "~1.7.0",
 "angular-elastic": "~2.5.1",
 "angular-material": "~1.0.9",
 "angular-google-analytics": "~1.1.7",
 "angular-animate": "~1.4.12",
 "angular-aria": "~1.4.12",
 "angular-messages": "~1.4.12",
 "ng-rollbar": "^1.9.2"
},
"resolutions": {
  "angular": "~1.4.12"
}
```

Then I created a file named app/assets/javascripts/config/ngrollbar.js where the rollbar gets initiallize:

```
app.config(function(ngRollbarProvider) {
  RollbarProvider.init({
   accessToken: "<MY-APPLICATION-TOKEN>",
   captureUncaught: true,
   payload: {
    environment: 'production'
   }
 });
});
```

And added ngrollbar to app/assets/javascripts/config/app.js:

```
var app = angular.module('chat',
  [
   'pusher-angular',`enter code here`
   'luegg.directives',
   'ngRoute',
   'templates',
   'angularPayments',
   'angularMoment',
   'xeditable',
   'zInfiniteScroll',
   'toastr',
   'monospaced.elastic',
   'ngMaterial',
   'angular-google-analytics',
   'tandibar/ng-rollbar',
  ]).run(  ["$rootScope","$http","amMoment","editableOptions","editableThemes","$mdSidenav",'Analytics','ngrollbar', function($rootScope , $http , amMoment , editableOptions , editableThemes , $mdSidenav , Analytics , ngrollbar) { ... }]);
```

In app/assets/javascripts/controllers/chat.js:

`app.controller("ChatController", [$scope","$rootScope","$http",'$pusher','$location','$routeParams','userProfile','toastr','flash','ngrollbar', function($scope , $rootScope , $http , $pusher , $location , $routeParams , userProfile , toastr , flash , ngrollbar ) {...}]);`

And in app/assets/javascripts/application.js I have added: //= require ng-rollbar

When I try to run my app I get this message in the browser console:

> Error: [$injector:modulerr] Failed to instantiate module chat due to:
> [$injector:unpr] Unknown provider: ngRollbarProvider

I am not sure if it is a specific problem of ng-rollbar or I am missing some step in the process of adding a new module to my RoR+AngularJS app but I can't figure out what I am doing wrong.

**Comment by tandibar** [comment]
Hi, i think it is just a naming confusion: You have to inject 'Rollbar' instead of 'ngrollbar'.

    app.controller("ChatController", [$scope","$rootScope","$http",'$pusher','$location','$routeParams','userProfile','toastr','flash','Rollbar', function($scope , $rootScope , $http , $pusher , $location , $routeParams , userProfile , toastr , flash , Rollbar ) {...}]);

**Comment by develaper** [comment]
Thanks so much @tandibar !
It works. Happiest monday at work ever!
