### ISSUE TITLE
Uncaught TypeError: Illegal invocation error when RollbarProvider is configured with verbose: true

### ISSUE THREAD

**Issue by ryaa** [tandibar/ng-rollbar#31]
When RollbarProvider.init is configured with verbose true and the code invokes Rollbar.error Uncaught TypeError: Illegal invocation occurs.

The problem is experienced in ionic/cordova application with the latest crosswalk:

Cordova CLI: 6.4.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.3.0
Ionic CLI Version: 1.7.6
Ionic App Lib Version: 0.6.2
ios-deploy version: 1.9.1
ios-sim version: 5.0.13
OS: Mac OS X El Capitan
Node Version: v4.7.0
Xcode version: Xcode 8.3.2 Build version 8E2002

Changing verbose: to false fixes the problem

**Comment by tandibar** [comment]
I just updated to version 2.3.1. Could you please check if this issue still exists?
