### ISSUE TITLE
disable "captureUncaught" exceptions

### ISSUE THREAD

**Issue by eczajk1** [tandibar/ng-rollbar#35]
I have been able to use this repo (v1.9.2) by implementing the config block as described in the readme:

```js
myApp.config(['RollbarProvider', function(RollbarProvider) {
  RollbarProvider.init({
    accessToken: "<YOUR-APPLICATION-TOKEN>",
    captureUncaught: true,
    payload: {
      environment: '<specify-your-env>'
    }
  });
}]);
```

Things are working, but I want to disable logging to Rollbar in my dev environment.   So I figured I should just set ```captureUncaught``` to ```false```, but errors are still being logged to Rollbar.  Am I just misunderstanding ```captureUncaught```?

I do realize ```captureUncaught``` is a Rollbar config parameter, but I'll take any help you can offer.  Thanks!

**Comment by rokob** [comment]
You probably just need to set `enabled: false` in your config, captureUncaught only deals with uncaught exceptions, so you would still see direct `Rollbar.error` calls being logged.

**Comment by eczajk1** [comment]
Yep, that's what I was looking for.  Thanks!
