### ISSUE TITLE
Internal error TypeError: a.apply is not a function

### ISSUE THREAD

**Issue by FaberYeah** [tandibar/ng-rollbar#40]
Hello,

I get this error both with both ng-rollbar 2.2.3 and 2.2.4, in the RollbarProvider.init() call, with pre-existing working code. I get this error only using ng-rollbar.min.js , no errors with ng-rollbar.js

Maybe there's an error in the minified version?

Thanks

F.

**Comment by mobuchowski** [comment]
I have the same error.

**Comment by kepeket** [comment]
I got it too.

**Comment by rmeritz** [comment]
I got it too. 

I was able to get around it by checking out the `1.9.2` tag of this repo and replacing the `rollbar.js` snippet with latest snippet.

Snippet to replace:
https://github.com/tandibar/ng-rollbar/blob/1.9.1/ng-rollbar.js#L32

New Snippet.
https://github.com/rollbar/rollbar.js/blob/v2.2.4/dist/rollbar.min.js

**Comment by tandibar** [comment]
I just updated to version 2.3.1. Could you please check if this issue still exists?

**Comment by FaberYeah** [comment]
Hello,

I confirm that the bug is still there :-(

Now even the ng-rollbar.js file (not minified) gives error 

> Uncaught SyntaxError: Unexpected string at ng-rollbar.js:32

Could this be fixed?

Thank you

F.

**Comment by tandibar** [comment]
Sorry, just published 2.3.2 which should fix the syntax error...

**Comment by FaberYeah** [comment]
With 2.3.2 I got another error:

> Uncaught SyntaxError: Unexpected token } at ng-rollbar.js:127

...and the minified version continues to give errors :-(

**Comment by jpike88** [comment]
I'll take care of it, looks like an accidental copy paste

**Comment by FaberYeah** [comment]
Thank you @jpike88 . Are you in charge of both bugs? (minified / not minified)

**Comment by jpike88** [comment]
I just merged from someone who got to it before I did. Check the latest release, issue should be resolved now

**Comment by jpike88** [comment]
If not, please let me know and I'll reopen

**Comment by ahc2483** [comment]
I am having this same issue, using the latest release unfortunately.

**Comment by jpike88** [comment]
@ahc2483 How are you accessing this release, is it via bower?

**Comment by ahc2483** [comment]
I downloaded a zip of the latest from Github

**Comment by kstraszewski** [comment]
Hey, I download version 2.3.3, and i recive this errors on *.min.js:
1. a.apply is not a function
2. Cannot read property 'loadFull' of undefined

but, when i import regular *.js version:
1. Unexpected token :
2. Cannot read property 'module' of undefined

**Comment by ahc2483** [comment]
I saw the same exact results as well.

**Comment by jpike88** [comment]
I'm on it, turns out the version tracking code I stripped wasn't all of it. Whoops... just need a minute to fix this

**Comment by jpike88** [comment]
Alright, all should be resolved in release 2.3.5, let me know if issues persist

**Comment by ahc2483** [comment]
Awesome thank you!

**Comment by FaberYeah** [comment]
I couldn't find 2.3.5 via yarn/npm, maybe it still have to be updated there? (last available version: 2.3.2)

Thank you

**Comment by jpike88** [comment]
'npm publish' would need to be done by @tandibar

**Comment by jpike88** [comment]
hey @tandibar if you want to add me as an owner to the npm package I'm happy to help there too. My npm username is 'pikatore'

**Comment by tandibar** [comment]
@jpike88 done

**Comment by jpike88** [comment]
2.3.5 has been published to npm

**Comment by FaberYeah** [comment]
Hello,

thank you for the 2.3.5 version on npm, the non-minified version works beautifully now.

However, I continue to get errors using ng-rollbar.min.js, this is the traceback copied by Chromium console:

> ng-rollbar.min.js:32 [Rollbar]: Internal error TypeError: a.apply is not a function
    at ng-rollbar.min.js:32
    at Object.f [as setupShim] (ng-rollbar.min.js:32)
    at Object.<anonymous> (ng-rollbar.min.js:32)
    at b (ng-rollbar.min.js:32)
    at ng-rollbar.min.js:32
    at Object.init (ng-rollbar.min.js:32)
    at app.js:89
    at Object.invoke (angular.js:5040)
    at d (angular.js:4927)
    at angular.js:4937
(anonymous) @ ng-rollbar.min.js:32
f @ ng-rollbar.min.js:32
(anonymous) @ ng-rollbar.min.js:32
b @ ng-rollbar.min.js:32
(anonymous) @ ng-rollbar.min.js:32
init @ ng-rollbar.min.js:32
(anonymous) @ app.js:89
invoke @ angular.js:5040
d @ angular.js:4927
(anonymous) @ angular.js:4937
p @ angular.js:410
g @ angular.js:4917
hb @ angular.js:4839
c @ angular.js:1949
Uc @ angular.js:1970
we @ angular.js:1855
(anonymous) @ angular.js:33884
j @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
S @ jquery.min.js:3
jquery.min.js:2 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.6.6/$injector/modulerr?p0=pycoApp&p1=TypeError%3A%20Cannot%20read%20property%20'loadFull'%20of%20undefined%0A%20%20%20%20at%20Object.%3Canonymous%3E%20(http%3A%2F%2Facme.pyco.io%3A8000%2Fstatic%2Fdeps%2Fng-rollbar%2Fng-rollbar.min.js%3A6%3A1548)%0A%20%20%20%20at%20b%20(http%3A%2F%2Facme.pyco.io%3A8000%2Fstatic%2Fdeps%2Fng-rollbar%2Fng-rollbar.min.js%3A6%3A1199)%0A%20%20%20%20at%20http%3A%2F%2Facme.pyco.io%3A8000%2Fstatic%2Fdeps%2Fng-rollbar%2Fng-rollbar.min.js%3A6%3A1286%0A%20%20%20%20at%20Object.init%20(http%3A%2F%2Facme.pyco.io%3A8000%2Fstatic%2Fdeps%2Fng-rollbar%2Fng-rollbar.min.js%3A6%3A1291)%0A%20%20%20%20at%20http%3A%2F%2Facme.pyco.io%3A8000%2Fstatic%2Fjs%2Fangularjs%2Fapp.js%3A89%3A25%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2Facme.pyco.io%3A8000%2Fstatic%2Fdeps%2Fangular%2Fangular.min.js%3A44%3A357)%0A%20%20%20%20at%20d%20(http%3A%2F%2Facme.pyco.io%3A8000%2Fstatic%2Fdeps%2Fangular%2Fangular.min.js%3A42%3A237)%0A%20%20%20%20at%20http%3A%2F%2Facme.pyco.io%3A8000%2Fstatic%2Fdeps%2Fangular%2Fangular.min.js%3A42%3A376%0A%20%20%20%20at%20p%20(http%3A%2F%2Facme.pyco.io%3A8000%2Fstatic%2Fdeps%2Fangular%2Fangular.min.js%3A8%3A7)%0A%20%20%20%20at%20g%20(http%3A%2F%2Facme.pyco.io%3A8000%2Fstatic%2Fdeps%2Fangular%2Fangular.min.js%3A42%3A138)
    at angular.js:88
    at angular.js:4957
    at p (angular.js:410)
    at g (angular.js:4917)
    at hb (angular.js:4839)
    at c (angular.js:1949)
    at Uc (angular.js:1970)
    at we (angular.js:1855)
    at HTMLDocument.<anonymous> (angular.js:33884)
    at j (jquery.min.js:2)
(anonymous) @ angular.js:88
(anonymous) @ angular.js:4957
p @ angular.js:410
g @ angular.js:4917
hb @ angular.js:4839
c @ angular.js:1949
Uc @ angular.js:1970
we @ angular.js:1855
(anonymous) @ angular.js:33884
j @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
r.readyException @ jquery.min.js:2
(anonymous) @ jquery.min.js:2
j @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
k @ jquery.min.js:2
setTimeout (async)
(anonymous) @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
fire @ jquery.min.js:2
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
ready @ jquery.min.js:2
S @ jquery.min.js:3


Where's the problem? I'm the only one having this?

TY

F.

**Comment by jpike88** [comment]
Bizarre... I thought I squashed it. I'll give it another look this weekend

**Comment by jpike88** [comment]
Looks like the built in uglify is breaking it. I tried the npm uglifyjs CLI tool and it isn't erroring for me. Try latest release now guys (2.3.8)

**Comment by FaberYeah** [comment]
Thank you @jpike88 , now it seems to work fine!

Have a nice day :)

**Comment by FaberYeah** [comment]
@jpike88 , on version 2.3.9 the _a.apply is not a function_ error is still alive... Can you have a look at it?

**Comment by jpike88** [comment]
@FaberYeah @AlexeyToksarov can one of you please add a test for the .min.js file, or confirm that an update of grunt-contrib-uglify fixes the minified output? The last accepted PR passed the built-in tests, but it looks like they're simply not enough.

I barely have time to scratch my butt right now, this will be resolved quicker if someone can step in and help.

**Comment by AlexeyToksarov** [comment]
@jpike88  Looks like with grunt-contrib-uglify `^1.0.0` it's working for me

**Comment by jpike88** [comment]
ok rolling with that, lemme know if that breaks it too... i'll let you know when its out, and keep the issue open until i get a confirmation

**Comment by jpike88** [comment]
ok its up as 2.3.10, @FaberYeah let me know if this fixes it for you

**Comment by FaberYeah** [comment]
Thank you @jpike88 , 2.3.10 seems to work fine  :-)
