### ISSUE TITLE
Update to rollbar.js 2.2.9

### ISSUE THREAD

**Issue by yanigisawa** [tandibar/ng-rollbar#41]
A function was added [2.2.4 of rollbar.js](https://github.com/rollbar/rollbar.js/blob/master/CHANGELOG.md#v224) that I would like to use. Specifically the `telemetryScrubber` function. From what I can see of ng-rollbar's history, it is currently targeting 2.2.3 of rollbar.js. 

Are there any blockers preventing ng-rollbar from upgrading to rollbar.js 2.2.9?

**Comment by idostern** [comment]
+1

**Comment by ecuzziol** [comment]
+1

**Comment by masmerino13** [comment]
+1

**Comment by jiarongxu** [comment]
2.2.9 now +1

**Comment by tandibar** [comment]
I just updated to version 2.3.1. As I am no longer developing AngularJS Apps, it is getting harder for me to maintain this library. If someone is interested in contributing, please let me know. I would be happy to find some collaborators.
