### ISSUE TITLE
Abandon repo or add more contributors

### ISSUE THREAD

**Issue by jpike88** [tandibar/ng-rollbar#42]
This is getting a little silly... you have an outstanding pull request that is more than 3 months old...

If you don't want to continue to work on this repo that's fine, but you have a responsibility to the community here that uses it... all you have to do is either bring it up to speed (it is really out of date with respect to the Rollbar.js version now), or just add some more contributors who can help get this thing back up to scratch.

**Comment by tandibar** [comment]
I just updated to version 2.3.1. As I am no longer developing AngularJS Apps, it is getting harder for me to maintain this library. If you are interested in contributing, please let me know. I would be happy to add you as a collaborator.

**Comment by jpike88** [comment]
Im happy to be a contributor, I’ll be working with angular 1.x for the long run.

Thanks
