### ISSUE TITLE
Namespace Rollbar instance

### ISSUE THREAD

**Issue by Synergi** [tandibar/ng-rollbar#52]
We are in a bit of a bind. We have a telephony application that is written with Angular 1.5. The app is designed to be integrated into the client's CRM product. Usually running in an iframe. We implemented Rollbar into our app some time ago and as yet we have not been able to get any data coming back when the app is integrated into Zendesk. (Salesforce and ServiceNow both work fine.)

Looking through the network data, etc when in Zendesk I can see that they are also loading Rollbar and this has been confirmed by the guys at Rollbar as well.

Could it be that our issue is down to a conflict with the version being run in the parent window? If so, is there any way we might be able to namespace or isolate our own Rollbar instance?

Thanks in advance. We would really appreciate any assistance with this.

**Comment by jpike88** [comment]
We're not a part of the rollbar team, so I think the help I can give is limited here.

I would suggest asking them if putting it another namespace isn't going to cause any weird side effects. If they're cool with it, then we can move forward in implementing it.

**Comment by Synergi** [comment]
I have been discussing this with the Rollbar guys and they initially stated that if we use the native rollbar.js it "supports creating a _rollbar_ instance in the scope of your app." They suggested I make a query here to see if that would be possible with your implementation.

**Comment by jpike88** [comment]
Ah I see, a good question. My response would be, would initialising rollbar in app scope affect global error detection? If it just does what I think it does and listens for global error events, theoretically it could work. You’re free to tweak the library to have it set it in some sort of app wide scope, as long as it doesn’t break existing usage scenarios. Feel free to submit a PR and I will verify it works my end
