### ISSUE TITLE
update to rollbar.js version 1.7.1

### ISSUE THREAD

**Issue by didlich** [tandibar/ng-rollbar#7]
there is a new rollbar version

**Comment by tandibar** [comment]
minified snippet version in 1.7.1 seems to be broken. Updated to 1.7.0

**Comment by brianr** [comment]
@tandibar What was the problem with snippet version 1.7.1?

**Comment by tandibar** [comment]
This is how i expect the script to be: https://github.com/rollbar/rollbar.js/blob/v1.7.0/dist/rollbar.snippet.js
but in version 1.7.1 it looks like this: https://github.com/rollbar/rollbar.js/blob/v1.7.1/dist/rollbar.snippet.js
I am not sure what happend in 1.7.1 but on master it looks good.
